name: Release to MSI

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup Windows SDK
      uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.5
    - name: Add github source
      run: dotnet nuget add source --username AkiEvansDev --password ${{ secrets.TOKEN_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/AkiEvansDev/index.json"
    - name: Setup VS Dev Environment
      uses: seanmiddleditch/gha-setup-vsdevenv@v4
    - name: Build the Installer
      run: DevEnv AE.ScreenWorker.sln /project ScreenWorkerInstaller/ScreenWorkerInstaller.vdproj /rebuild Release
    - name: Get version
      uses: kzrnm/get-net-sdk-project-versions-action@v1
      id: get-version
      with:
        proj-path: ./ScreenWorkerWPF/ScreenWorkerWPF.csproj
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: ./ScreenWorkerInstaller/Release/ScreenWorkerInstaller.msi
        asset_name: ScreenWorkerSetup${{steps.get-version.outputs.version}}.msi
        asset_content_type: application/octet-stream
